apiVersion: apps/v1
kind: Deployment
metadata:
  name: infraasset-api
  labels:
    app: infraasset-api
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: infraasset-api
  template:
    metadata:
      labels:
        app: infraasset-api
    spec:
      containers:
        - name: api
          image: {{ .Values.image.api }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 8080
          env:
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: infraasset-db
                  key: url
            - name: APP_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: infraasset-app
                  key: secret
            - name: APP_ENV
              value: {{ .Values.env | quote }}
            - name: WEB_ORIGIN
              value: {{ .Values.webOrigin | quote }}
            - name: DEMO_SEED
              value: {{ .Values.demoSeed | quote }}
          readinessProbe:
            httpGet:
              path: /healthz
              port: http
            initialDelaySeconds: 8
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /healthz
              port: http
            initialDelaySeconds: 20
            periodSeconds: 20
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
---
apiVersion: v1
kind: Service
metadata:
  name: infraasset-api
spec:
  selector:
    app: infraasset-api
  ports:
    - name: http
      port: 8080
      targetPort: http
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: infraasset-web
  labels:
    app: infraasset-web
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: infraasset-web
  template:
    metadata:
      labels:
        app: infraasset-web
    spec:
      containers:
        - name: web
          image: {{ .Values.image.web }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 3000
          env:
            - name: NODE_ENV
              value: production
            - name: HOSTNAME
              value: "0.0.0.0"
            - name: PORT
              value: "3000"
            - name: API_INTERNAL_URL
              value: http://infraasset-api:8080
          readinessProbe:
            httpGet:
              path: /login
              port: http
            initialDelaySeconds: 8
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /login
              port: http
            initialDelaySeconds: 20
            periodSeconds: 20
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
---
apiVersion: v1
kind: Service
metadata:
  name: infraasset-web
spec:
  selector:
    app: infraasset-web
  ports:
    - name: http
      port: 80
      targetPort: http
