apiVersion: v1
kind: Secret
metadata:
  name: infraasset-db
  labels:
    app.kubernetes.io/name: infraasset
type: Opaque
stringData:
  username: {{ .Values.postgresql.username | quote }}
  password: {{ .Values.postgresql.password | quote }}
  database: {{ .Values.postgresql.database | quote }}
  url: {{ printf "postgresql+psycopg://%s:%s@infraasset-postgres:5432/%s" .Values.postgresql.username .Values.postgresql.password .Values.postgresql.database | quote }}
---
apiVersion: v1
kind: Secret
metadata:
  name: infraasset-app
  labels:
    app.kubernetes.io/name: infraasset
type: Opaque
stringData:
  secret: {{ default "change-me-infraasset-kind" .Values.appSecret | quote }}
