ASSET_TYPES = [
    "server",
    "cpu",
    "gpu",
    "memory",
    "disk",
    "nic",
    "switch",
    "router",
    "firewall",
    "load_balancer",
    "access_point",
    "storage",
    "hypervisor",
    "vm",
    "container",
    "kubernetes_cluster",
    "kubernetes_node",
    "pod",
    "rack",
    "pdu",
    "ups",
    "generator",
    "cdu",
    "pump",
    "chiller",
    "cooling_tower",
    "heat_exchanger",
    "cold_plate",
    "rack_manifold",
    "sensor",
    "application",
    "database",
    "cloud_resource",
    "ats",
    "transformer",
    "busway",
    "crac",
    "crah",
]

RELATIONSHIP_TYPES = [
    "CONTAINS",
    "HOSTS",
    "RUNS_ON",
    "CONNECTED_TO",
    "DEPENDS_ON",
    "POWERED_BY",
    "COOLED_BY",
    "STORED_ON",
    "MEMBER_OF",
    "MANAGED_BY",
    "PROTECTED_BY",
    "BACKED_UP_TO",
    "USES",
    "ROUTES_THROUGH",
    "DEPLOYED_ON",
    "MONITORED_BY",
]

ASSET_STATUSES = [
    "online",
    "offline",
    "warning",
    "critical",
    "maintenance",
    "unknown",
    "stale",
    "decommissioned",
]
ENVIRONMENTS = ["production", "uat", "development", "dr", "lab"]
CRITICALITY = ["critical", "high", "medium", "low"]
HEALTH = ["healthy", "degraded", "unhealthy", "unknown"]
